language: python

python:
  - "2.7"
  - "3.6"
  - "pypy"

before_install:
  - pip install pip -U
  - pip install pypoet
  - poet make:setup -v
  - pip uninstall pypoet -y
  - python setup.py develop
  - pip install codecov
  - poet --version
  - poet install -v

script: py.test --cov=poet --cov-config=.coveragerc tests/

after_success:
  - codecov
