[package]
name = "pypoet"
version = "0.3.1"
description = "Poet helps you declare, manage and install dependencies of Python projects, ensuring you have the right stack everywhere."

license = "MIT"

authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]

readme = 'README.md'

repository = "https://github.com/sdispater/poet"
homepage = "https://github.com/sdispater/poet"

keywords = ['packaging', 'poet']

include = ['poet/**/*', 'LICENSE']

python = ["~2.7", "^3.5"]


[features]
markdown-readme = ["pypandoc"] # Adds support for markdown readmes

[dependencies]
toml = "^0.9"
requests = "^2.13"
semantic_version = "^2.6"
pygments = "^2.2"
twine = "^1.8"
wheel = "^0.29"
pip-tools = "^1.9.0-rc.2"
cleo = { git = "https://github.com/sdispater/cleo.git", branch = "develop" }
pathlib2 = "^2.2"  # Only needed for Python 2.7

# Extras
pypandoc = { version = "^1.3.3", optional = true }

[dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"
pytest-mock = "^1.6"
coverage = "^3.7"
httpretty = "^0.8.14"


[scripts]
poet = 'poet:app.run'
