[package]
name = "package-dir-example"
version = "0.1.0"
description = "Package dir example"

license = "MIT"

authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]

readme = "README.rst"

homepage = "https://github.com/sdispater/poet"

keywords = ['packaging', 'poet']

include = [
    {from = 'src', include = '**/*'}
]

python = ["^3.5"]


[dependencies]
requests = "^2.13"

[dev-dependencies]
pytest = "^3.0"
