[package]
name = "basic-example"
version = "0.1.0"
description = "Basic example"

license = "MIT"

authors = [
    "Sébastien Eustace <sebastien@eustace.io>"
]

readme = "README.rst"

homepage = "https://github.com/sdispater/poet"

keywords = ['packaging', 'poet']

include = ['cli_app/**/*']

python = ["^3.5"]


[dependencies]
cleo = "^0.5.0"

[dev-dependencies]
pytest = "^3.0"


[scripts]
"mycli" = "cli_app:app.run"
